services:
  build-rms:
    build:
      context: .
      dockerfile: Dockerfile 
    image: memberlite/rms-docker-img:v5
    container_name: rms-docker-container-ecologea
    ports:
      - "8000:5050" 
